# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  publish:
    name: Code analysis, clean, test, build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Sonar continuous inspection of code quality and security
        run: ./gradlew sonar
      - name: Run build with Gradle Wrapper
        run: ./gradlew build